# Generated by Django 4.1.3 on 2022-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_a', models.CharField(max_length=100)),
                ('direccion_a', models.CharField(max_length=200)),
                ('edad_a', models.IntegerField()),
                ('Pais_a', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('tiempo_mes', models.IntegerField()),
                ('costo_mes', models.IntegerField()),
            ],
        ),
    ]
