# Generated by Django 4.1.3 on 2022-12-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_amigos_carros_escuelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigos',
            old_name='Pais_a',
            new_name='Pais',
        ),
        migrations.RenameField(
            model_name='amigos',
            old_name='direccion_a',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='amigos',
            old_name='edad_a',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='amigos',
            old_name='nombre_a',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='carros',
            old_name='direccion',
            new_name='origen',
        ),
    ]
